### ISSUE TITLE
Connecting to Facebook Messenger or Slack

### ISSUE THREAD

**Issue by github-contenta** [MishUshakov/dialogflow-gateway#1]
Hi, I'm in the research period of tools for building bots. I'm now looking at Dialogflow, and one of it's downsides is that it has no native support for Webchat UI. I see that you made one, that's really cool. I tested it (with this project and the web-v2 one) and works really well.

As I now have a working server handling requests to Google, I figured I could see if I could build some analytics on top of it. It's just for research purposes, to see if it's possible. My idea is adding a request to a service of mine every time a request goes to Dialogflow. This will work well with the webchat, but I was wondering if I could also use it with Facebook Messenger and Slack.

I see that Dialogflow has some direct integrations for those, but I couldn't get in the middle of the requests if I opt for that option. I noticed that you mention those platforms in your README.md. Is it possible to use this gateway to integrate Dialogflow with Facebook Messenger and Slack. If so, how?

Thank you!

**Comment by MishUshakov** [comment]
Ok, alright
I understand the problem you are trying to solve here.
Since the requests, that are coming from messengers are sent to Dialogflow directly, you can not gather analytics using the gateway (it's only used as adapter for HTTP Clients, like Dialogflow for Web)
You can not track how requests are coming in and out of Dialogflow, for that, you will need a webhook

Here is how it works the standard way, if using WebUI:
HTTP Client -> Gateway -> Dialogflow

My customer wanted to gather analytics from Google Assistant, here is how he solved the problem:

Google Assistant -> Dialogflow -> Webhook

And the same works for Web:
WebUI -> Gateway -> Dialogflow -> Webhook

The web hook is used for gathering analytics, but the responses are coming from Dialogflow

Thank you for using my product. Hope it's clear for you and your question resolved.
