### ISSUE TITLE
Bug with some fulfillments

### ISSUE THREAD

**Issue by github-contenta** [MishUshakov/dialogflow-gateway#2]
Hello. I believe there is a bug with how some fulfillments are implemented. If in Dialogflow I set the response to Facebook Messeger and a Quick Replies response, the title is ignored and only replies are shown. This is the json:

```
        {
          "platform": "FACEBOOK",
          "quickReplies": {
            "quickReplies": [
              "Reply 1",
              "Reply 2"
            ],
            "title": "This is the title"
          },
          "message": "quickReplies"
        }
```

I then tried adding the title to the default response in Dialogflow, and also checking "Use response from the DEFAULT tab as the first response.".

I know get this json:

```
        {
          "platform": "FACEBOOK",
          "text": {
            "text": [
              "This is the default text response"
            ]
          },
          "message": "text"
        },
        {
          "platform": "PLATFORM_UNSPECIFIED",
          "text": {
            "text": [
              "This is the default text response"
            ]
          },
          "message": "text"
        },
        {
          "platform": "FACEBOOK",
          "quickReplies": {
            "quickReplies": [
              "Reply 1",
              "Reply 2"
            ],
            "title": "This is the title"
          },
          "message": "quickReplies"
        }
```

As you can see, this time the text appears twice, and because of how it is implemented it is shown twice on the webchat.

I think a solution would be not ignoring the title field of the quickReplies, so that way you could avoid using the Default Response that is duplicating the text.

**Comment by MishUshakov** [comment]
Hello dear @github-contenta!
Since you are not using my formatting feature in your example, the responses are not pre-formatted before they are being sent to client.

Instead they directly come from Dialogflow V2 API! And it's, as you guessed it...

![iu](https://user-images.githubusercontent.com/10400064/52798496-54e4cb80-3078-11e9-9dfd-895c0cfa5362.jpeg)

And now you have got the ultimate chance, to experience, how fu*ked up the DialogFlow API is! You can of course contact their support and raise your issue there. But don't expect any changes soon (I'll bet you will have to wait a year or two, to them to get that fixed).

I'm really sorry, that you have to experience this. It's such a shame for @google, to deliver such a bad quality of their product!

They could just hire me to fix those things up, but they won't! They need an Indian to do that (no hate, just kidding!).

I wish a happy Valentines Day to you and your loved ones, Anonymus! And thank you for using my product 👍

**Comment by github-contenta** [comment]
What do you mean by not using the formatting feature? When I point the webchat of your other repository to this gateway, I see both messages there as well. Do I have to enable something? I see that the REST request coming from the webchat have `?format=true` set, is that what you mean? This is the reply this gateway gives when DialogFlow sends the JSON I mentioned:

```
{
	"id": "f41c5180-0c1e-4c43-b398-09836b024f5d",
	"action": "",
	"query": "botones",
	"params": {
		"fields": {}
	},
	"diagnosticInfo": null,
	"components": [{
		"name": "DEFAULT",
		"content": "This is the default text response"
	}, {
		"name": "DEFAULT",
		"content": "This is the default text response"
	}, {
		"name": "SUGGESTIONS",
		"content": ["Reply 1", "Reply 2"]
	}]
}
```

As you can see, both texts are there as well.

**Comment by MishUshakov** [comment]
Yeah, that's the way it is currently implemented on Google's side. But that's how Dialogflow works. Im just providing the functionality of Dialogflow to HTTP-Clients. And no more. My client renders responses from all sources, at the same time (because, I can not know, which sources you want to have). I think you should try to customise the Gateway, so it fits best for your needs. Thank you.
